// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeLn11bPL180OrM1U94TOSSnFq6kGdUTc',
    appId: '1:107109077440:web:01718f26ac6130d9d3b825',
    messagingSenderId: '107109077440',
    projectId: 'flutterxp-f8cde',
    authDomain: 'flutterxp-f8cde.firebaseapp.com',
    storageBucket: 'flutterxp-f8cde.firebasestorage.app',
    measurementId: 'G-V7Y6M32K75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC86wjAMMkhc62l07fnnsPjvJUvtDSqkFo',
    appId: '1:107109077440:android:8a01fa938a68b2a1d3b825',
    messagingSenderId: '107109077440',
    projectId: 'flutterxp-f8cde',
    storageBucket: 'flutterxp-f8cde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLISSEA615rJqDbKLgOE_IIsyX-roMPjQ',
    appId: '1:107109077440:ios:7f84bad6f1044d28d3b825',
    messagingSenderId: '107109077440',
    projectId: 'flutterxp-f8cde',
    storageBucket: 'flutterxp-f8cde.firebasestorage.app',
    iosBundleId: 'com.example.helloflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLISSEA615rJqDbKLgOE_IIsyX-roMPjQ',
    appId: '1:107109077440:ios:7f84bad6f1044d28d3b825',
    messagingSenderId: '107109077440',
    projectId: 'flutterxp-f8cde',
    storageBucket: 'flutterxp-f8cde.firebasestorage.app',
    iosBundleId: 'com.example.helloflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeLn11bPL180OrM1U94TOSSnFq6kGdUTc',
    appId: '1:107109077440:web:6f39ac3901285adcd3b825',
    messagingSenderId: '107109077440',
    projectId: 'flutterxp-f8cde',
    authDomain: 'flutterxp-f8cde.firebaseapp.com',
    storageBucket: 'flutterxp-f8cde.firebasestorage.app',
    measurementId: 'G-CGDR42B93E',
  );
}
